// For user authentication
export const REQUEST_LOADING = "REQUEST_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const CURRENT_LOGGEDIN_USER = "CURRENT_LOGGEDIN_USER"
export const CURRENT_LOGGEDIN_USER_FAIL = "CURRENT_LOGGEDIN_USER_FAIL"
export const VIEWED_LOGGEDIN_USER = "VIEWED_LOGGEDIN_USER"
export const SET_USER_TOKEN = "SET_USER_TOKEN"
export const UNFOLLOW_USER = "UNFOLLOW_USER"
export const UPDATE_FAIL = " UPDATE_FAIL"


// for polls
export const ALLPOLL = "ALLPOLL";
export const CREATEPOLL = "CREATEPOLL"
export const SINGLEPOLL = "SINGLEPOLL"
export const SINGLEPOLL_FAIL = "SINGLEPOLL_FAIL"
export const CREATEPOLL_FAIL = "CREATEPOLL_FAIL"
export const ALLPOLL_FAIL = "ALLPOLL_FAIL"
export const VOTE_FAIL = "VOTE_FAIL"
export const LIKE_POLL = "LIKE_POLL"

export const MESSAGE = "MESSAGE"